services:
  docs:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ALLOWED_ORIGINS=${BASE_DOMAIN},www.${BASE_DOMAIN}
    restart: unless-stopped
    networks:
      - traefik-public
    environment:
      - ALLOWED_ORIGINS=${BASE_DOMAIN},www.${BASE_DOMAIN}
    labels:
      - traefik.enable=${ENABLE_TRAEFIK:-false}
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public
      # Main domain route
      - traefik.http.routers.docs-base.rule=Host(`${BASE_DOMAIN}`)
      - traefik.http.routers.docs-base.entrypoints=web
      - "${HTTPS_MIDDLEWARE:+traefik.http.routers.docs-base.middlewares=${HTTPS_MIDDLEWARE}}"
      - traefik.http.routers.docs-base-secure.rule=Host(`${BASE_DOMAIN}`)
      - traefik.http.routers.docs-base-secure.entrypoints=${HTTPS_ENTRYPOINT:-}
      - traefik.http.routers.docs-base-secure.tls=${ENABLE_TLS:-}"
      - traefik.http.routers.docs-base-secure.tls.certresolver=${TLS_RESOLVER:-}
      - traefik.http.routers.docs.rule=Host(`www.${BASE_DOMAIN}`)
      - traefik.http.routers.docs.entrypoints=web
      - "${HTTPS_MIDDLEWARE:+traefik.http.routers.docs.middlewares=${HTTPS_MIDDLEWARE}}"
      - traefik.http.routers.docs-secure.rule=Host(`www.${BASE_DOMAIN}`)
      - traefik.http.routers.docs-secure.entrypoints=${HTTPS_ENTRYPOINT:-}
      - traefik.http.routers.docs-secure.tls=${ENABLE_TLS:-}"
      - traefik.http.routers.docs-secure.tls.certresolver=${TLS_RESOLVER:-}
      - traefik.http.services.docs.loadbalancer.server.port=3000
      - "${REDIRECT_SCHEME:+traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=${REDIRECT_SCHEME}}"
      - "${REDIRECT_PERMANENT:+traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=${REDIRECT_PERMANENT}}"

networks:
  traefik-public:
    external: ${ENABLE_TRAEFIK:-false}
    name: ${TRAEFIK_NETWORK:-traefik-public}
