services:
  hedgedoc_database:
    image: postgres:13.4-alpine
    env_file:
     - ./.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - internal
  hedgedoc:
    # Make sure to use the latest release from https://hedgedoc.org/latest-release
    image: quay.io/hedgedoc/hedgedoc:1.10.0
    env_file:
     - ./.env
    environment:
      - CMD_DB_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@hedgedoc_database:5432/${POSTGRES_DB}
      - CMD_DOMAIN=hedgedoc.${BASE_DOMAIN}
      - CMD_PROTOCOL_USESSL=true
      - CMD_URL_ADDPORT=false
      - CMD_SESSION_SECRET=${HD_SESSION_SECRET}
      - CMD_CSP_ENABLE=true
      - CMD_HELMET_ENABLE=true
    volumes:
      - uploads:/hedgedoc/public/uploads
    networks:
      - internal
      - traefik-public
    labels:
      - traefik.enable=${ENABLE_TRAEFIK:-false}
      - traefik.docker.network=traefik-public
      - traefik.http.routers.hedgedoc.rule=Host(`hedgedoc.${BASE_DOMAIN}`)
      - traefik.http.routers.hedgedoc.entrypoints=web
      - "${HTTPS_MIDDLEWARE:+traefik.http.routers.hedgedoc.middlewares=${HTTPS_MIDDLEWARE}}"
      - traefik.http.routers.hedgedoc-secure.rule=Host(`hedgedoc.${BASE_DOMAIN}`)
      - traefik.http.routers.hedgedoc-secure.entrypoints=${HTTPS_ENTRYPOINT:-}
      - traefik.http.routers.hedgedoc-secure.tls=${ENABLE_TLS:-}"
      - traefik.http.routers.hedgedoc-secure.tls.certresolver=${TLS_RESOLVER:-}
      - traefik.http.services.hedgedoc.loadbalancer.server.port=3000
      - "${REDIRECT_SCHEME:+traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=${REDIRECT_SCHEME}}"
      - "${REDIRECT_PERMANENT:+traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=${REDIRECT_PERMANENT}}"
    restart: always
    depends_on:
      - hedgedoc_database
volumes:
  database:
  uploads:
networks:
  internal:
  traefik-public:
    external: ${ENABLE_TRAEFIK:-false}
    name: ${TRAEFIK_NETWORK:-traefik-public}
