services:
  baserow:
    image: baserow/baserow:1.29.3
    env_file: ./baserow.env
    networks:
      - internal
      - traefik-public
    volumes:
      - baserow_data:/baserow/data
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.baserow.rule=Host(`baserow.${BASE_DOMAIN}`)
        - traefik.http.routers.baserow.entrypoints=https
        - traefik.http.routers.baserow.tls=true
        - traefik.http.routers.baserow.tls.certresolver=le
        - traefik.http.services.baserow.loadbalancer.server.port=80
        - traefik.http.services.baserow.loadbalancer.passHostHeader=true
networks:
  internal:
    driver: overlay
  traefik-public:
    external: true

volumes:
  baserow_data:
    driver: local