services:
  baserow:
    image: baserow/baserow:1.30.1
    environment:
      BASEROW_PUBLIC_URL: '${HTTP_SCHEME}://baserow.${BASE_DOMAIN}'
    env_file:
      - ./.env
    networks:
      - internal
      - traefik-public
    volumes:
      - ./data/baserow:/baserow/data
    labels:
      - traefik.enable=${ENABLE_TRAEFIK:-false}
      - traefik.docker.network=traefik-public
      - traefik.http.routers.baserow.rule=Host(`baserow.${BASE_DOMAIN}`)
      - traefik.http.routers.baserow.entrypoints=web
      - "${HTTPS_MIDDLEWARE:+traefik.http.routers.baserow.middlewares=${HTTPS_MIDDLEWARE}}"
      - traefik.http.routers.baserow-secure.rule=Host(`baserow.${BASE_DOMAIN}`)
      - traefik.http.routers.baserow-secure.entrypoints=${HTTPS_ENTRYPOINT:-}
      - traefik.http.routers.baserow-secure.tls=${ENABLE_TLS:-}"
      - traefik.http.routers.baserow-secure.tls.certresolver=${TLS_RESOLVER:-}
      - traefik.http.services.baserow.loadbalancer.server.port=80
      - "${REDIRECT_SCHEME:+traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=${REDIRECT_SCHEME}}"
      - "${REDIRECT_PERMANENT:+traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=${REDIRECT_PERMANENT}}"
networks:
  internal:
    driver: bridge
  traefik-public:
    external: ${ENABLE_TRAEFIK:-false}
    name: ${TRAEFIK_NETWORK:-traefik-public}